### ISSUE TITLE
GIS connection

### ISSUE THREAD

**Issue by mzur** [biigle/geo#18]
The Geomar people suggested, that, rather than implementing more and more GIS features in BIIGLE, BIIGLE should rather get an interface to a GIS like QGIS. By exporting annotations (and their positions), as well as maybe image thumbnails to a GIS, we would not need to implement #17, #16, #3 and #1 ourselves.

With the Web Tile Service support mentioned im #11, any visualizations etc. created with the GIS could be made available in BIIGLE again.

**Comment by tschoeni** [comment]
This could also come in the form of an API endpoint that serves information from the BIIGLE data base in e.g. WMS format. Could become a login credential issue for non-public data?!

**Comment by mzur** [comment]
> Could become a login credential issue for non-public data?!

If the GIS doesn't support API authentication, the API URL could include a unique authentication token. This shouldn't be an issue.

**Comment by mzur** [comment]
For the record: A standardized way for BIIGLE to provide annotation data would be a WFS server ([which is compatible with QGIS](https://docs.qgis.org/3.4/en/docs/user_manual/working_with_ogc/ogc_client_support.html)). Other formats are presented on [this page](https://docs.qgis.org/3.4/en/docs/user_manual/working_with_ogc/ogc_client_support.html).

**Comment by mzur** [comment]
I found that WFS is quite a complex standard and (apparently) no implementation exists for PHP. GeoJSON may be a simpler alternative. GeoJSON vector sources via HTTP are supported by QGIS.

Besides: QGIS also supports authentication via HTTP.

**Comment by mzur** [comment]
In the GIS, it should be possible to:

- Show the image locations of a project/volume on a map
- Filter the images of a project/volume by occurrence of annotations with a certain label
- Visualize the abundancy of annotations with a certain label in project/volume images
- Show the (estimated) annotation locations of a project/volume/image on a map
- Filter the images of a project/volume by their image labels

**Comment by mzur** [comment]
An experimental GIS connection through GeoJSON API endpoints has been implemented in #24. I'm wondering if we should change the implementation from API endpoints to "GeoJSON reports" that can be downloaded as files. Reports have the advantage that the files don't change and they are generated asynchronously (i.e. support large numbers of images/annotations). API endpoints can only support a limited number of annotations because of the response timeout of 30 s.

**Comment by mzur** [comment]
I decided to implement this as reports, instead. This has the additional benefit that reports are archived and users can utilize the existing filter options for reports.
