### ISSUE TITLE
Key for rectangle creation in geo filter does not work for mac

### ISSUE THREAD

**Issue by dlangenk** [biigle/geo#63]
The description in the geofilter is "To do this, press and hold Ctrl as well as the left mouse button and move the cursor on the map."

On Mac this does not work and the CMD Key must be used instead. I would change the description to Ctrl/CMD.

**Comment by mtiessen1175** [comment]
Good point, that's fixed now (0c4efb70679505b9836d01b3d945d7b98e7a50f9)!
